/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { BamlRuntime, FunctionResult, BamlCtxManager, BamlStream, Image, ClientRegistry, toBamlError, Audio } from "@boundaryml/baml"
import { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type { partial_types } from "./partial_types"
import {BFlow, BFlowJsonEdge, BFlowJsonNode, BFlowNode, BFlowNodeConfig, BFlowNodeState, BFlowNodeType, BFlowViz, EchoBack, Position} from "./types"
import * as types from "./types"
import type TypeBuilder from "./type_builder"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

/**
 * @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
 */
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>

export class BamlAsyncClient {
  private runtime: BamlRuntime
  private ctx_manager: BamlCtxManager
  private stream_client: BamlStreamClient

  constructor(runtime: BamlRuntime, ctx_manager: BamlCtxManager) {
    this.runtime = runtime
    this.ctx_manager = ctx_manager
    this.stream_client = new BamlStreamClient(runtime, ctx_manager)
  }

  get stream() {
    return this.stream_client
  }

  
  async Echo(
      message: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Promise<EchoBack> {
    try {
      const raw = await this.runtime.callFunction(
        "Echo",
        {
          "message": message
        },
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return raw.parsed(false) as EchoBack
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  async ParseBFlowToBFlowViz(
      bflow: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Promise<BFlowViz> {
    try {
      const raw = await this.runtime.callFunction(
        "ParseBFlowToBFlowViz",
        {
          "bflow": bflow
        },
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return raw.parsed(false) as BFlowViz
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  async ParseMarkdocBFlowElementToBFlow(
      text: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Promise<BFlow> {
    try {
      const raw = await this.runtime.callFunction(
        "ParseMarkdocBFlowElementToBFlow",
        {
          "text": text
        },
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return raw.parsed(false) as BFlow
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
}

class BamlStreamClient {
  constructor(private runtime: BamlRuntime, private ctx_manager: BamlCtxManager) {}

  
  Echo(
      message: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): BamlStream<partial_types.EchoBack, EchoBack> {
    try {
      const raw = this.runtime.streamFunction(
        "Echo",
        {
          "message": message
        },
        undefined,
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return new BamlStream<partial_types.EchoBack, EchoBack>(
        raw,
        (a): partial_types.EchoBack => a,
        (a): EchoBack => a,
        this.ctx_manager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ParseBFlowToBFlowViz(
      bflow: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): BamlStream<partial_types.BFlowViz, BFlowViz> {
    try {
      const raw = this.runtime.streamFunction(
        "ParseBFlowToBFlowViz",
        {
          "bflow": bflow
        },
        undefined,
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return new BamlStream<partial_types.BFlowViz, BFlowViz>(
        raw,
        (a): partial_types.BFlowViz => a,
        (a): BFlowViz => a,
        this.ctx_manager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ParseMarkdocBFlowElementToBFlow(
      text: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): BamlStream<partial_types.BFlow, BFlow> {
    try {
      const raw = this.runtime.streamFunction(
        "ParseMarkdocBFlowElementToBFlow",
        {
          "text": text
        },
        undefined,
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return new BamlStream<partial_types.BFlow, BFlow>(
        raw,
        (a): partial_types.BFlow => a,
        (a): BFlow => a,
        this.ctx_manager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export const b = new BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)