/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { Image } from "@boundaryml/baml"

import * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}


export interface BFlow {
    id: ((string | null) | null)
    name: ((string | null) | null)
    description: ((string | null) | null)
    root?: partial_types.BFlowNode | null
}

export interface BFlowData {
    nodes?: partial_types.BFlowJsonNode | null[]
    edges?: partial_types.BFlowJsonEdge | null[]
}

export interface BFlowJsonEdge {
    id: ((string | null) | null)
    source: ((string | null) | null)
    target: ((string | null) | null)
}

export interface BFlowJsonNode {
    type?: (BFlowNodeType | null)
    id: ((string | null) | null)
    name: ((string | null) | null)
    description: ((string | null) | null)
    parentId: ((string | null) | null)
    config: (partial_types.BFlowNodeConfig | null | null)
    position?: partial_types.Position | null
}

export interface BFlowNode {
    type?: (BFlowNodeType | null)
    id: ((string | null) | null)
    name: ((string | null) | null)
    description: ((string | null) | null)
    config: (partial_types.BFlowNodeConfig | null | null)
    goto?: partial_types.BFlowNode | null[]
}

export interface BFlowNodeConfig {
    id: ((string | null) | null)
    name?: (string | null)
    url: ((string | null) | null)
    instructions: ((string | null) | null)
}

export interface EchoBack {
    message?: (string | null)
    messageBack?: (string | null)
}

export interface Position {
    x?: (number | null)
    y?: (number | null)
}
