/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"

/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum BFlowNodeState {
  RUNNING = "RUNNING",
  SUCCESS = "SUCCESS",
  FAILURE = "FAILURE",
}

export enum BFlowNodeType {
  ENTRY = "ENTRY",
  FAILBACK = "FAILBACK",
  SEQUENCE = "SEQUENCE",
  PARALLEL = "PARALLEL",
  CONDITION = "CONDITION",
  ACTION = "ACTION",
}

export interface BFlow {
  id?: string | null
  name?: string | null
  description?: string | null
  root: BFlowNode
  
}

export interface BFlowData {
  nodes: BFlowJsonNode[]
  edges: BFlowJsonEdge[]
  
}

export interface BFlowJsonEdge {
  id?: string | null
  source?: string | null
  target?: string | null
  
}

export interface BFlowJsonNode {
  type: BFlowNodeType
  id?: string | null
  name?: string | null
  description?: string | null
  parentId?: string | null
  config?: BFlowNodeConfig | null
  position: Position
  
}

export interface BFlowNode {
  type: BFlowNodeType
  id?: string | null
  name?: string | null
  description?: string | null
  config?: BFlowNodeConfig | null
  state?: BFlowNodeState | null
  goto: BFlowNode[]
  
}

export interface BFlowNodeConfig {
  yaml?: string | null
  
}

export interface EchoBack {
  message: string
  messageBack: string
  
}

export interface Position {
  x: number
  y: number
  
}
